server:
  port: 8761

spring:
  application:
    # ?? ?? ID
    name: discoveryservice



eureka:
  client:
    # ??? ????? ??? ??
    # ??? ??? ???? ???? ?? False
    register-with-eureka: false
    fetch-registry: false
