spring:
  application:
    name: user-service

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /console

  datasource:
    url: jdbc:h2:~/db
    username: sa
  jpa:
    hibernate:
      ddl-auto: update


  cloud:
    config:
      name: ecommerce # yml 파일명 앞부분
  config:
    import: optional:configserver:http://localhost:8888 # 구성정보 설정


server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    # ??? ??? ?? ???.
    register-with-eureka: true
    # ????? ?????? ??? ????? ?????? ???? ??(??? ??? ???.)
    fetch-registry: true
    service-url:
      # ??? ??? url
      defaultZone: http://localhost:8761/eureka

greeting:
  message: Welcome to the User-Service



