

spring:
  application:
    name: first-service

server:
  port: 8081

eureka:
  client:
    # ??? ????? ??? ??
    # ??? ??? ???? ???? ?? False
    register-with-eureka: false
    fetch-registry: false
