spring:
  application:
    name: second-service

server:
  port: 8082

eureka:
  client:
    # ??? ????? ??? ??
    # ??? ??? ???? ???? ?? False
    register-with-eureka: false
    fetch-registry: false
